In [22]:
#1,8,2,0,4,3,7,6,5
#1,2,0,4,5,3,7,8,6

#unsolvable
#8,1,2,0,4,3,7,6,5


#Defining Goal and initial States
import numpy as np
from copy import deepcopy
import heapq
import math
goal = np.array([1,2,3,4,5,6,7,8,0]).reshape(3,3)
print(goal)
print()
start_state = np.array([8,1,2,0,4,3,7,6,5]).reshape(3,3)
print(start_state)




[[1 2 3]
 [4 5 6]
 [7 8 0]]

[[8 1 2]
 [0 4 3]
 [7 6 5]]


In [23]:
#checking if coming state already in openlist

def isdictVisited(state,vis):
  flag1=0
  for i in vis:
    if (state==(np.fromstring(i,dtype=state.dtype).reshape(3,3))).all()==True:
      flag1=1
      break
  if flag1==1:
    return True
  else:
    return False

In [24]:
#checking if current state in closedList

def isVisited(state,vis):
  flag=0
  for i in vis:
    if (state==i).all()==True:
      flag=1
      break
  if flag==1:
    return True
  else:
    return False

In [25]:
#Checking if current state is Goal

def isGoal(state):
  return (goal==state).all()

In [26]:
#if current state already in openList then Update its f(N) in the Hash Table

def update_in_Hash(myhash,state,state_fn):
    state_bytes = state.tostring()
    if myhash[state_bytes]>state_fn:
        myhash[state_bytes]=state_fn

In [27]:
#Get Manhattan Heuristic Value of a particular state

def get_heuristics(state):
    coord_list=[]
    state_list=[]
    for i in range(3):
        for j in range(3):
            coord_list.append([i,j])
#     print(state)
    for i in range(8):
        k=list(np.where(state==i+1))
#         print(k)
        state_list.append([k[0][0],k[1][0]])
    heur = 0
    for i in range(8):
        heur = heur + abs(coord_list[i][0]-state_list[i][0]) + abs(coord_list[i][1]-state_list[i][1])
    return heur
        

In [30]:
#Finds state with minimum f(N) and expands it to find other state and recursively calls the next states to add into the Hash
#find thier minimum everytime and Finally reach the goal state if possible.
#I am taking key of matrix in Hash as a string to save space

def findGoal(curr_state,gn,openlist,closedlist,opit):
  if isGoal(np.array(curr_state)):
    print("Congrats you reached the goal\n",curr_state)
    
    return True
  elif opit>2000:
    return False
  else:
    
    possib = [[0,-1],[1,0],[0,1],[-1,0]]
   
    solution = False
    least_state_bytes = min(openlist, key=openlist.get)
    least_state = (np.fromstring(least_state_bytes,dtype=curr_state.dtype)).reshape(3,3)
    print("Curr State :\n", least_state,"\n")
    del openlist[least_state_bytes]
    closedlist.append(least_state)
    myI,myJ=map(int,np.where(least_state==0))
    for i,j in possib:
      
      if (myI+i>=0 and myJ+j<3 and myI+i<3 and myJ+j>=0):
        
        next_state = deepcopy(least_state)
        temp = least_state[myI+i][myJ+j]
        next_state[myI+i][myJ+j] = 0
        next_state[myI][myJ] = temp
        if isdictVisited(next_state,openlist.keys()):
            update_in_Hash(openlist,next_state,get_heuristics(next_state)+gn)
        elif not isVisited(next_state,closedlist):
          next_state_bytes = next_state.tostring()
          openlist[next_state_bytes]=get_heuristics(next_state)+gn
        else:
            next_state = deepcopy(least_state)
    
    
    solution = findGoal(least_state,gn+1,openlist,closedlist,opit+1)
    return solution




In [31]:
#The main calling function that takes data of initial configuration and calls findGoal to search for th goal


hn=get_heuristics(start_state)
# openlist=heapq.heapify([[0+hn,start_state]])
oplist={}
closedlist=[]
start_state_bytes = start_state.tostring()
oplist[start_state_bytes]=hn
# oplist.append(start_state)
opit=0
x=findGoal(start_state,1,oplist,closedlist,opit)


if x==False:
    print("Solution not found! Enter a configuration which is solvable")

c:\users\subham\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
c:\users\subham\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


Curr State :
 [[8 1 2]
 [0 4 3]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [4 0 3]
 [7 6 5]] 

Curr State :
 [[0 1 2]
 [8 4 3]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [4 6 3]
 [7 0 5]] 

Curr State :
 [[1 0 2]
 [8 4 3]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [4 6 3]
 [7 5 0]] 

Curr State :
 [[8 1 2]
 [7 4 3]
 [0 6 5]] 

Curr State :
 [[8 1 2]
 [4 3 0]
 [7 6 5]] 

Curr State :
 [[8 0 2]
 [4 1 3]
 [7 6 5]] 

Curr State :
 [[1 2 0]
 [8 4 3]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [4 6 3]
 [0 7 5]] 

Curr State :
 [[1 4 2]
 [8 0 3]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [4 6 0]
 [7 5 3]] 

Curr State :
 [[1 2 3]
 [8 4 0]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [4 3 5]
 [7 6 0]] 

Curr State :
 [[0 8 2]
 [4 1 3]
 [7 6 5]] 

Curr State :
 [[8 2 0]
 [4 1 3]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [7 4 3]
 [6 0 5]] 

Curr State :
 [[8 1 0]
 [4 3 2]
 [7 6 5]] 

Curr State :
 [[1 2 3]
 [8 4 5]
 [7 6 0]] 

Curr State :
 [[1 4 2]
 [0 8 3]
 [7 6 5]] 

Curr State :
 [[1 4 2]
 [8 6 3]
 [7 0 5]] 

Curr State :
 [[8 1 2]
 [4 0 6]


 [[1 2 3]
 [6 0 4]
 [8 7 5]] 

Curr State :
 [[0 2 3]
 [1 6 4]
 [8 7 5]] 

Curr State :
 [[2 0 3]
 [1 4 5]
 [8 7 6]] 

Curr State :
 [[8 3 1]
 [4 6 2]
 [0 7 5]] 

Curr State :
 [[1 2 3]
 [8 5 6]
 [7 0 4]] 

Curr State :
 [[1 2 3]
 [7 8 5]
 [4 0 6]] 

Curr State :
 [[2 8 3]
 [1 0 4]
 [7 6 5]] 

Curr State :
 [[2 3 0]
 [1 8 4]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [7 4 6]
 [5 3 0]] 

Curr State :
 [[8 1 2]
 [7 0 6]
 [5 4 3]] 

Curr State :
 [[2 0 3]
 [1 8 5]
 [7 4 6]] 

Curr State :
 [[4 8 1]
 [7 3 2]
 [0 6 5]] 

Curr State :
 [[4 8 1]
 [3 0 2]
 [7 6 5]] 

Curr State :
 [[1 0 2]
 [8 5 3]
 [7 4 6]] 

Curr State :
 [[0 3 1]
 [8 4 2]
 [7 6 5]] 

Curr State :
 [[1 2 3]
 [8 6 0]
 [4 7 5]] 

Curr State :
 [[8 3 1]
 [7 4 2]
 [0 6 5]] 

Curr State :
 [[8 1 3]
 [0 2 5]
 [7 4 6]] 

Curr State :
 [[1 3 5]
 [8 2 0]
 [7 4 6]] 

Curr State :
 [[1 0 2]
 [8 7 3]
 [6 4 5]] 

Curr State :
 [[1 6 2]
 [0 8 3]
 [4 7 5]] 

Curr State :
 [[1 6 2]
 [8 7 3]
 [4 0 5]] 

Curr State :
 [[1 6 2]
 [8 3 0]
 [4 7 5]] 

C

Curr State :
 [[8 1 2]
 [6 0 7]
 [4 5 3]] 

Curr State :
 [[8 1 0]
 [6 7 2]
 [4 5 3]] 

Curr State :
 [[8 2 3]
 [6 0 1]
 [4 7 5]] 

Curr State :
 [[0 8 1]
 [7 3 2]
 [6 4 5]] 

Curr State :
 [[8 3 1]
 [7 0 2]
 [6 4 5]] 

Curr State :
 [[8 1 2]
 [6 3 5]
 [0 4 7]] 

Curr State :
 [[8 1 2]
 [6 0 5]
 [4 3 7]] 

Curr State :
 [[6 8 2]
 [4 1 3]
 [0 7 5]] 

Curr State :
 [[6 8 2]
 [1 0 3]
 [4 7 5]] 

Curr State :
 [[4 8 1]
 [6 5 2]
 [7 0 3]] 

Curr State :
 [[4 8 1]
 [6 2 0]
 [7 5 3]] 

Curr State :
 [[4 0 1]
 [6 8 2]
 [7 5 3]] 

Curr State :
 [[0 8 1]
 [4 5 2]
 [7 3 6]] 

Curr State :
 [[4 8 1]
 [7 6 2]
 [5 0 3]] 

Curr State :
 [[8 5 1]
 [4 0 2]
 [7 3 6]] 

Curr State :
 [[1 3 4]
 [8 6 2]
 [7 5 0]] 

Curr State :
 [[1 3 2]
 [8 0 5]
 [4 7 6]] 

Curr State :
 [[1 2 0]
 [8 3 5]
 [4 7 6]] 

Curr State :
 [[1 3 4]
 [7 8 2]
 [0 6 5]] 

Curr State :
 [[0 3 4]
 [1 8 2]
 [7 6 5]] 

Curr State :
 [[1 3 4]
 [8 6 2]
 [0 7 5]] 

Curr State :
 [[8 6 1]
 [4 2 3]
 [7 0 5]] 

Curr State :
 [[8 2 3]
 [4 0 6]


Curr State :
 [[1 6 2]
 [4 8 3]
 [7 0 5]] 

Curr State :
 [[4 8 1]
 [7 3 2]
 [6 5 0]] 

Curr State :
 [[3 1 0]
 [8 4 2]
 [7 6 5]] 

Curr State :
 [[1 3 5]
 [0 8 2]
 [7 4 6]] 

Curr State :
 [[1 3 5]
 [8 4 2]
 [7 0 6]] 

Curr State :
 [[8 0 3]
 [2 1 5]
 [7 4 6]] 

Curr State :
 [[4 8 1]
 [7 0 2]
 [6 3 5]] 

Curr State :
 [[3 4 1]
 [8 0 2]
 [7 6 5]] 

Curr State :
 [[1 0 5]
 [8 3 2]
 [7 4 6]] 

Curr State :
 [[6 0 2]
 [1 8 3]
 [4 7 5]] 

Curr State :
 [[1 2 3]
 [8 7 0]
 [6 4 5]] 

Curr State :
 [[1 6 2]
 [8 7 0]
 [4 5 3]] 

Curr State :
 [[8 3 1]
 [7 4 2]
 [6 5 0]] 

Curr State :
 [[1 6 2]
 [8 3 5]
 [4 0 7]] 

Curr State :
 [[1 6 2]
 [0 7 3]
 [8 4 5]] 

Curr State :
 [[1 7 2]
 [0 8 3]
 [6 4 5]] 

Curr State :
 [[1 7 2]
 [8 4 3]
 [6 0 5]] 

Curr State :
 [[1 0 6]
 [8 3 2]
 [4 7 5]] 

Curr State :
 [[1 3 4]
 [8 2 5]
 [0 7 6]] 

Curr State :
 [[1 3 4]
 [8 0 5]
 [7 2 6]] 

Curr State :
 [[1 4 2]
 [3 5 0]
 [8 7 6]] 

Curr State :
 [[1 0 2]
 [3 4 5]
 [8 7 6]] 

Curr State :
 [[1 7 2]
 [8 3 0]


Curr State :
 [[1 2 0]
 [7 4 8]
 [6 5 3]] 

Curr State :
 [[1 4 2]
 [7 5 8]
 [6 3 0]] 

Curr State :
 [[1 2 3]
 [7 8 6]
 [5 0 4]] 

Curr State :
 [[0 1 2]
 [7 4 8]
 [6 5 3]] 

Curr State :
 [[2 0 3]
 [1 8 6]
 [7 5 4]] 

Curr State :
 [[0 2 3]
 [1 7 5]
 [4 8 6]] 

Curr State :
 [[4 8 2]
 [7 5 1]
 [6 0 3]] 

Curr State :
 [[4 0 2]
 [7 8 1]
 [6 5 3]] 

Curr State :
 [[1 4 2]
 [6 7 8]
 [0 5 3]] 

Curr State :
 [[4 8 2]
 [0 7 1]
 [6 5 3]] 

Curr State :
 [[4 0 8]
 [7 1 2]
 [6 5 3]] 

Curr State :
 [[0 4 2]
 [1 7 8]
 [6 5 3]] 

Curr State :
 [[1 4 2]
 [7 3 5]
 [0 6 8]] 

Curr State :
 [[4 2 0]
 [1 7 3]
 [6 8 5]] 

Curr State :
 [[0 1 4]
 [7 8 2]
 [6 5 3]] 

Curr State :
 [[1 8 4]
 [7 0 2]
 [6 5 3]] 

Curr State :
 [[1 4 2]
 [7 0 5]
 [6 3 8]] 

Curr State :
 [[0 6 2]
 [4 1 3]
 [8 7 5]] 

Curr State :
 [[4 7 2]
 [1 0 3]
 [6 8 5]] 

Curr State :
 [[4 6 2]
 [1 7 3]
 [0 8 5]] 

Curr State :
 [[4 6 2]
 [1 7 3]
 [8 5 0]] 

Curr State :
 [[4 6 2]
 [8 1 3]
 [0 7 5]] 

Curr State :
 [[4 6 2]
 [1 3 5]


Curr State :
 [[1 2 3]
 [8 7 5]
 [6 4 0]] 

Curr State :
 [[4 8 1]
 [7 2 0]
 [6 3 5]] 

Curr State :
 [[4 0 1]
 [7 8 2]
 [6 3 5]] 

Curr State :
 [[1 2 3]
 [8 0 7]
 [6 4 5]] 

Curr State :
 [[4 8 1]
 [0 7 2]
 [6 3 5]] 

Curr State :
 [[1 6 2]
 [8 0 7]
 [4 5 3]] 

Curr State :
 [[1 6 0]
 [8 7 2]
 [4 5 3]] 

Curr State :
 [[1 6 2]
 [7 0 3]
 [8 4 5]] 

Curr State :
 [[1 6 2]
 [8 3 5]
 [0 4 7]] 

Curr State :
 [[1 6 2]
 [8 0 5]
 [4 3 7]] 

Curr State :
 [[0 6 2]
 [1 7 3]
 [8 4 5]] 

Curr State :
 [[8 3 1]
 [7 4 0]
 [6 5 2]] 

Curr State :
 [[1 7 2]
 [6 8 3]
 [0 4 5]] 

Curr State :
 [[1 3 6]
 [8 0 2]
 [4 7 5]] 

Curr State :
 [[1 3 4]
 [0 2 5]
 [8 7 6]] 

Curr State :
 [[1 7 2]
 [8 4 3]
 [0 6 5]] 

Curr State :
 [[1 7 2]
 [8 4 3]
 [6 5 0]] 

Curr State :
 [[1 3 4]
 [0 8 5]
 [7 2 6]] 

Curr State :
 [[1 3 4]
 [8 5 0]
 [7 2 6]] 

Curr State :
 [[1 4 2]
 [3 5 6]
 [8 7 0]] 

Curr State :
 [[0 7 2]
 [1 8 3]
 [6 4 5]] 

Curr State :
 [[0 1 6]
 [8 3 2]
 [4 7 5]] 

Curr State :
 [[1 2 0]
 [3 4 5]


 [[8 2 5]
 [4 1 6]
 [0 7 3]] 

Curr State :
 [[8 2 5]
 [4 0 6]
 [7 1 3]] 

Curr State :
 [[6 4 1]
 [8 5 2]
 [7 0 3]] 

Curr State :
 [[6 4 1]
 [8 2 0]
 [7 5 3]] 

Curr State :
 [[0 8 1]
 [3 5 2]
 [4 7 6]] 

Curr State :
 [[1 2 6]
 [8 5 3]
 [4 7 0]] 

Curr State :
 [[3 8 2]
 [4 1 5]
 [0 7 6]] 

Curr State :
 [[3 8 2]
 [1 0 5]
 [4 7 6]] 

Curr State :
 [[8 5 1]
 [3 0 2]
 [4 7 6]] 

Curr State :
 [[1 2 6]
 [8 0 5]
 [4 7 3]] 

Curr State :
 [[4 2 3]
 [0 8 5]
 [1 7 6]] 

Curr State :
 [[4 8 2]
 [7 1 5]
 [3 6 0]] 

Curr State :
 [[4 8 2]
 [7 0 5]
 [3 1 6]] 

Curr State :
 [[8 2 5]
 [3 1 6]
 [4 7 0]] 

Curr State :
 [[8 2 5]
 [3 0 1]
 [4 7 6]] 

Curr State :
 [[1 5 2]
 [4 8 6]
 [0 7 3]] 

Curr State :
 [[0 5 2]
 [1 8 6]
 [4 7 3]] 

Curr State :
 [[8 1 4]
 [3 6 2]
 [7 5 0]] 

Curr State :
 [[8 2 5]
 [4 3 1]
 [0 7 6]] 

Curr State :
 [[8 2 5]
 [4 3 1]
 [7 6 0]] 

Curr State :
 [[8 1 4]
 [3 2 5]
 [7 6 0]] 

Curr State :
 [[8 1 0]
 [3 2 4]
 [7 6 5]] 

Curr State :
 [[8 1 4]
 [3 6 2]
 [0 7 5]] 

C

 [[1 4 2]
 [6 5 7]
 [8 0 3]] 

Curr State :
 [[1 0 2]
 [6 4 7]
 [8 5 3]] 

Curr State :
 [[1 4 2]
 [0 3 5]
 [6 8 7]] 

Curr State :
 [[7 1 4]
 [0 3 2]
 [6 8 5]] 

Curr State :
 [[1 0 4]
 [6 7 2]
 [8 5 3]] 

Curr State :
 [[1 4 2]
 [0 6 5]
 [8 3 7]] 

Curr State :
 [[1 4 2]
 [6 5 0]
 [8 3 7]] 

Curr State :
 [[1 0 2]
 [6 4 5]
 [8 3 7]] 

Curr State :
 [[4 2 3]
 [7 8 5]
 [6 1 0]] 

Curr State :
 [[1 6 2]
 [8 5 3]
 [7 4 0]] 

Curr State :
 [[1 6 2]
 [7 8 3]
 [0 5 4]] 

Curr State :
 [[0 6 2]
 [1 8 3]
 [7 5 4]] 

Curr State :
 [[4 2 3]
 [7 0 8]
 [6 1 5]] 

Curr State :
 [[1 6 2]
 [8 5 3]
 [0 7 4]] 

Curr State :
 [[1 6 2]
 [8 3 4]
 [7 5 0]] 

Curr State :
 [[1 3 4]
 [6 7 2]
 [8 0 5]] 

Curr State :
 [[8 1 2]
 [7 6 3]
 [0 5 4]] 

Curr State :
 [[8 1 2]
 [6 0 3]
 [7 5 4]] 

Curr State :
 [[1 6 0]
 [8 3 2]
 [7 5 4]] 

Curr State :
 [[8 2 6]
 [1 0 3]
 [4 7 5]] 

Curr State :
 [[0 2 6]
 [8 1 3]
 [4 7 5]] 

Curr State :
 [[0 2 6]
 [8 4 3]
 [7 1 5]] 

Curr State :
 [[1 2 3]
 [7 4 5]
 [0 6 8]] 

C

 [[1 2 3]
 [0 8 5]
 [4 6 7]] 

Curr State :
 [[1 2 3]
 [8 5 0]
 [4 6 7]] 

Curr State :
 [[1 0 3]
 [8 2 5]
 [4 6 7]] 

Curr State :
 [[1 2 0]
 [8 7 6]
 [5 4 3]] 

Curr State :
 [[8 1 2]
 [7 3 4]
 [0 5 6]] 

Curr State :
 [[1 7 2]
 [8 0 6]
 [5 4 3]] 

Curr State :
 [[8 1 2]
 [7 3 4]
 [5 6 0]] 

Curr State :
 [[8 1 2]
 [5 7 4]
 [0 3 6]] 

Curr State :
 [[0 1 2]
 [8 7 4]
 [5 3 6]] 

Curr State :
 [[0 8 2]
 [7 1 4]
 [5 3 6]] 

Curr State :
 [[8 2 0]
 [7 1 4]
 [5 3 6]] 

Curr State :
 [[0 8 1]
 [7 4 2]
 [5 3 6]] 

Curr State :
 [[7 8 2]
 [5 1 6]
 [0 4 3]] 

Curr State :
 [[7 8 2]
 [1 0 6]
 [5 4 3]] 

Curr State :
 [[1 3 5]
 [0 2 6]
 [8 7 4]] 

Curr State :
 [[8 1 2]
 [7 0 3]
 [5 6 4]] 

Curr State :
 [[8 2 6]
 [7 1 3]
 [5 4 0]] 

Curr State :
 [[1 3 5]
 [0 8 6]
 [7 2 4]] 

Curr State :
 [[8 4 1]
 [7 0 2]
 [5 3 6]] 

Curr State :
 [[4 8 1]
 [3 2 5]
 [0 7 6]] 

Curr State :
 [[4 8 1]
 [3 0 5]
 [7 2 6]] 

Curr State :
 [[1 3 5]
 [8 6 0]
 [7 2 4]] 

Curr State :
 [[1 0 5]
 [8 3 6]
 [7 2 4]] 

C

Curr State :
 [[8 3 4]
 [2 0 1]
 [7 6 5]] 

Curr State :
 [[8 1 2]
 [4 6 7]
 [5 0 3]] 

Curr State :
 [[8 1 2]
 [0 5 7]
 [6 4 3]] 

Curr State :
 [[8 2 3]
 [6 7 0]
 [4 5 1]] 

Curr State :
 [[6 8 2]
 [4 1 0]
 [7 5 3]] 

Curr State :
 [[6 8 2]
 [0 1 7]
 [4 5 3]] 

Curr State :
 [[6 8 3]
 [0 2 1]
 [4 7 5]] 

Curr State :
 [[8 2 7]
 [6 1 0]
 [4 5 3]] 

Curr State :
 [[6 0 2]
 [4 8 3]
 [7 1 5]] 

Curr State :
 [[6 8 2]
 [0 4 3]
 [7 1 5]] 

Curr State :
 [[6 8 2]
 [4 3 0]
 [7 1 5]] 

Curr State :
 [[8 1 2]
 [4 6 5]
 [3 0 7]] 

Curr State :
 [[6 8 1]
 [0 7 2]
 [4 5 3]] 

Curr State :
 [[8 7 1]
 [0 6 2]
 [4 5 3]] 

Curr State :
 [[8 7 1]
 [6 5 2]
 [4 0 3]] 

Curr State :
 [[8 7 1]
 [6 2 0]
 [4 5 3]] 

Curr State :
 [[4 8 1]
 [6 2 3]
 [0 7 5]] 

Curr State :
 [[4 8 1]
 [6 0 3]
 [7 2 5]] 

Curr State :
 [[8 3 1]
 [7 2 5]
 [6 0 4]] 

Curr State :
 [[8 0 1]
 [6 5 2]
 [4 3 7]] 

Curr State :
 [[1 0 2]
 [8 3 5]
 [6 4 7]] 

Curr State :
 [[7 8 1]
 [6 3 2]
 [4 0 5]] 

Curr State :
 [[6 8 2]
 [1 7 0]


Curr State :
 [[2 6 3]
 [8 7 1]
 [4 0 5]] 

Curr State :
 [[8 1 4]
 [0 6 2]
 [3 7 5]] 

Curr State :
 [[1 5 2]
 [8 6 3]
 [4 0 7]] 

Curr State :
 [[4 2 3]
 [1 0 6]
 [7 5 8]] 

Curr State :
 [[8 1 4]
 [7 3 0]
 [6 5 2]] 

Curr State :
 [[2 0 5]
 [8 4 1]
 [7 3 6]] 

Curr State :
 [[4 2 0]
 [1 6 3]
 [7 5 8]] 

Curr State :
 [[8 1 4]
 [7 2 0]
 [6 3 5]] 

Curr State :
 [[8 4 2]
 [3 1 0]
 [7 6 5]] 

Curr State :
 [[1 5 2]
 [0 7 6]
 [8 4 3]] 

Curr State :
 [[8 1 4]
 [0 7 2]
 [6 3 5]] 

Curr State :
 [[8 0 4]
 [7 1 2]
 [6 3 5]] 

Curr State :
 [[8 6 1]
 [7 2 3]
 [5 4 0]] 

Curr State :
 [[1 0 2]
 [8 7 5]
 [3 4 6]] 

Curr State :
 [[4 8 5]
 [0 2 1]
 [7 3 6]] 

Curr State :
 [[1 5 2]
 [8 7 0]
 [4 3 6]] 

Curr State :
 [[1 2 3]
 [8 4 6]
 [0 5 7]] 

Curr State :
 [[0 2 3]
 [1 4 6]
 [8 5 7]] 

Curr State :
 [[8 6 0]
 [7 2 1]
 [5 4 3]] 

Curr State :
 [[1 2 3]
 [4 6 7]
 [8 5 0]] 

Curr State :
 [[1 2 0]
 [4 6 3]
 [8 5 7]] 

Curr State :
 [[0 1 3]
 [4 2 6]
 [8 5 7]] 

Curr State :
 [[1 3 0]
 [4 2 6]
