In [6]:
#1,8,2,0,4,3,7,6,5
#1,2,0,4,5,3,7,8,6

#unsolvable config
#8,1,2,0,4,3,7,6,5

import numpy as np
from copy import deepcopy
goal = np.array([1,2,3,4,5,6,7,8,0]).reshape(3,3)
print(goal)
print()
start_state = np.array([8,1,2,0,4,3,7,6,5]).reshape(3,3)
print(start_state)
reaches=[]
reaches.append(0)

[[1 2 3]
 [4 5 6]
 [7 8 0]]

[[8 1 2]
 [0 4 3]
 [7 6 5]]


In [7]:
#checking if current state in closedList

def isVisited(state,vis):
  flag=0
  for i in vis:
    if (state==i).all()==True:
      flag=1
      break
  if flag==1:
    return True
  else:
    return False


In [8]:

#Checking if current state is Goal

def isGoal(state):
  return (goal==state).all()

In [9]:
#Running Dfs with a limit increasing by small amount everytime
#Deepcopy ensures matrix call by value

def findGoal(curr_state,i,j,curr_visit,allowed,depth):
  
  if depth>allowed:
        return False
  elif isGoal(np.array(curr_state)):
    ans = curr_state
    print("Congrats you reached the goal\n",curr_state)
   
    return True
  else:
    
    myI=i
    myJ=j
    # myI,myJ=(np.where(curr_state==0))
    # myI=int(myI)
    # myJ=int(myJ)

 
    
   
    possib = [[0,-1],[1,0],[0,1],[-1,0]]
   
    solution = False
    
    for i,j in possib:
      
      if (myI+i>=0 and myJ+j<3 and myI+i<3 and myJ+j>=0):
        if not isVisited(curr_state,curr_visit):
        
          next_state = deepcopy(curr_state)
             
          next_visit = deepcopy(curr_visit)

          #Swap with 0 the actions
          temp = curr_state[myI+i][myJ+j]
          next_state[myI+i][myJ+j] = 0
          next_state[myI][myJ] = temp

          next_visit.append(curr_state)
          solution = findGoal(next_state,myI+i,myJ+j,next_visit,allowed,depth+1)
          if solution == True:
              return solution
    
    return solution




In [ ]:
#After 50 iterations(which is a lot) if solution is not found it stops and doesnt go further 

vis=[]
ans=np.zeros([3,3])
myI,myJ=(np.where(start_state==0))   #index where matrix has 0 as value
myI=int(myI)
myJ=int(myJ)
depth=0
for i in range(50):
    print("Starting ",i," th iteration")
    x=findGoal(start_state,myI,myJ,vis,i,depth)
    if x==True:
        break
if x==False:
    print("Solution not found")

Starting  0  th iteration
Starting  1  th iteration
Starting  2  th iteration
Starting  3  th iteration
Starting  4  th iteration
Starting  5  th iteration
Starting  6  th iteration
Starting  7  th iteration
Starting  8  th iteration
Starting  9  th iteration
Starting  10  th iteration
Starting  11  th iteration
Starting  12  th iteration
Starting  13  th iteration
Starting  14  th iteration
Starting  15  th iteration
Starting  16  th iteration
Starting  17  th iteration
Starting  18  th iteration
Starting  19  th iteration
Starting  20  th iteration
Starting  21  th iteration
Starting  22  th iteration
Starting  23  th iteration
